<a href="https://www.kaggle.com/code/himanshunakrani/numpy?scriptVersionId=106817154" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# What is NumPy?

- NumPy is the fundamental package for scientific computing in Python. it is used for working with arrays. 
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy stands for Numerical Python.

# install NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Why Use NumPy?

Even though Python lists are great on their own, NumPy has a number of key features that give it great advantages over Python lists.

### Benefits of using NumPy

**1) Speed** -  When performing operations on large arrays NumPy can often perform several orders of magnitude faster than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.<br> 
**2) multidimensional array data structures** -  NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently, making it very suitable for solving machine learning problems.<br>
**3) optimized built-in mathematical functions** - Another great advantage of NumPy over Python lists is that NumPy has a large number of optimized built-in mathematical functions. These functions allow you to do a variety of complex mathematical computations very fast and with very little code making your programs more readable and easier to understand.

## 1. Speed

In [2]:
# Why use NumPy?
import time
import numpy as np
x = np.random.random(100000000)

# Case 1
start = time.time()
sum(x) / len(x)
print("using built-in python function: ", time.time() - start)

# Case 2
start = time.time()
np.mean(x)
print("using NumPy: ", time.time() - start)

using built-in python function:  8.571125030517578
using NumPy:  0.07526278495788574


# Creating NumPy array

### 1. Using regular Python lists

In [3]:
import numpy as np

In [4]:
#  a 1-D Array of Integers (Rank #1 Array)

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print("rank: ", a.ndim)

rank:  1


In [6]:
print(a.shape)

(5,)


In [7]:
print(a.dtype)

int64


In [8]:
# 2-D Array (Rank #2 Array)

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
print(b.shape)

(3, 4)


In [10]:
print("rank: ", b.ndim)

rank:  2


In [11]:
# 1-D Array of Strings (Rank #1 Array)

c = np.array(["Hello", "World"])
print(c.dtype)

<U5


In [12]:
# 1-D Array of Int and String (Rank #1 Array)

d = np.array([1, 2, 3, "Hello"])
print(d.dtype)

<U21


In [13]:
# 1-D Array of Int and Float

e = np.array([1, 2.3, 5])
print(e.dtype)

float64


In [14]:
# 1-D Array of Float, and specifying the datatype of each element as int64

f = np.array([1, 2.3, 4], dtype = np.int64)
print(f.dtype)

int64


In [15]:
#  Save the NumPy array to a File
x = np.array([1, 2, 3, 4, 5])

# save x into the current directory as 'my_array'
np.save('my_array', x)

In [16]:
# load the saved array from current directory into variable y
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


### 2. Using built-in NumPy functions

In [17]:
# 3X4 ndarray full of zeros

X = np.zeros((3, 4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# 3X4 ndarray full of ones

Y = np.ones((3, 4))
print(Y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# 3X4 ndarray full of sevens

Z = np.full((3, 4), 7)
print(Z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [20]:
# 5X5 identity matrix

I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
# 4X4 diagonal matrix having diagonal values 1, 2, 3 and 4

D = np.diag([1, 2, 3, 4])
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [22]:
# rank 1 ndarray that has sequential integers from 0 to 9
N = np.arange(10)

# rank 1 ndarray that has sequential integers from 10 to 29
M = np.arange(10, 30)

# rank 1 ndarray that has evenly spaced integers from 10 to 30 in steps of 3
O = np.arange(10, 30, 3)
print(N)
print(M)
print(O)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[10 13 16 19 22 25 28]


In [23]:
# rank 1 ndarray that has 50 intgers evenly spaced between 10and 30
Q = np.linspace(10, 30, 50)
print(Q)

[10.         10.40816327 10.81632653 11.2244898  11.63265306 12.04081633
 12.44897959 12.85714286 13.26530612 13.67346939 14.08163265 14.48979592
 14.89795918 15.30612245 15.71428571 16.12244898 16.53061224 16.93877551
 17.34693878 17.75510204 18.16326531 18.57142857 18.97959184 19.3877551
 19.79591837 20.20408163 20.6122449  21.02040816 21.42857143 21.83673469
 22.24489796 22.65306122 23.06122449 23.46938776 23.87755102 24.28571429
 24.69387755 25.10204082 25.51020408 25.91836735 26.32653061 26.73469388
 27.14285714 27.55102041 27.95918367 28.36734694 28.7755102  29.18367347
 29.59183673 30.        ]


In [24]:
#  reshape M into a 5X4 ndarray
m = M.reshape(5, 4)
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]


In [25]:
n = np.arange(0, 100).reshape(10, 10)
print(n)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [26]:
# 3X3 ndarray with random floats in the half-open interval [0.0, 1.0)
r = np.random.random((5, 5))
print(r)

[[0.664303   0.75982243 0.60331268 0.05719099 0.98883569]
 [0.94642022 0.00727566 0.74106339 0.63462423 0.85267634]
 [0.4838914  0.13492824 0.23184515 0.54696489 0.67776049]
 [0.87153945 0.76079984 0.19512511 0.87793509 0.17102906]
 [0.35192727 0.2581351  0.94120919 0.33236762 0.09437818]]


In [27]:
#  5X4 ndarray with random integers in the half-open interval [4, 20)
r = np.random.randint(4, 20, (5, 4))
print(r)

[[19 13 18  5]
 [ 8 19 18 17]
 [ 5 12 11  5]
 [ 5  4 14 17]
 [ 4 18 17 10]]


In [28]:
# normal(Gaussian) distribution, mean = 0, standard deviation = 0.1

r = np.random.normal(0, 0.1, size = (100, 100))

print("mean: ", r.mean())
print("std: ", r.std())
print("max: ", r.max())
print("min: ", r.min())
print("Positive: ", (r>0).sum())
print("Negative: ", (r<0).sum())

mean:  -0.002005491985902655
std:  0.09996683053049149
max:  0.3390447195187352
min:  -0.35156965828091047
Positive:  4944
Negative:  5056


# Accessing, Deleting, and Inserting Elements Into ndarrays

In [29]:
# indexing

x = np.array([1, 2, 3, 4, 5])

In [30]:
print("1st element: ", x[0])
print("2nd element: ", x[1])
print("3rd element: ", x[2])
print("5th element: ", x[4])

1st element:  1
2nd element:  2
3rd element:  3
5th element:  5


In [31]:
# negative indexing
print("1st element: ", x[-5])
print("2nd element: ", x[-4])
print("3rd element: ", x[-3])
print("5th element: ", x[-1])


1st element:  1
2nd element:  2
3rd element:  3
5th element:  5


In [32]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print("element at (0, 0): ", y[0, 0])
print("element at (1, 2): ", y[1, 2])
print("element at (2, 1): ", y[2, 1])

element at (0, 0):  1
element at (1, 2):  6
element at (2, 1):  8


In [34]:
# modifying element

y[0, 0] = 100
print(y)


[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [35]:
# deleting element

X = np.delete(x, [0, 4])
print(X)

[2 3 4]


In [36]:
Y = np.delete(y, [0, 0])
print(Y)

[2 3 4 5 6 7 8 9]


In [37]:
# appending an element

W = np.append(y, [[10, 20, 30]], axis = 0)
print(W)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  20  30]]


In [38]:
V = np.append(y, [[10], [20], [30]], axis = 1)
print(V)

[[100   2   3  10]
 [  4   5   6  20]
 [  7   8   9  30]]


In [39]:
# inserting an element at a position

Z = np.insert(W, 2, [9, 8, 7], axis = 0)
print(Z)

[[100   2   3]
 [  4   5   6]
 [  9   8   7]
 [  7   8   9]
 [ 10  20  30]]


In [40]:
x = np.array([1,2])
y = np.array([[3,4],[5,6]])


# stack x on top of Y
K = np.vstack((x, y))
print("K:\n", K)

# x on the right of Y
M = np.hstack((y,x.reshape(2,1)))
print("M:\n", M)

K:
 [[1 2]
 [3 4]
 [5 6]]
M:
 [[3 4 1]
 [5 6 2]]


# Slicing ndarrays

- three types of slicing:

1. array[ start:end ]
2. array[ start: ]
3. array[ :end ]

start - inclusive
end - exclusive


In [41]:
X = np.arange(0, 20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [42]:
# [row, column]
y = X[1:3, 2:4]
print(y)

[[ 7  8]
 [12 13]]


In [43]:
# rows- second through last, columns- third through last
y = X[1:, 2:]
print(y)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [44]:
# rows- first through third, columns- first through second
y = X[:3, :2]
print(y)

[[ 0  1]
 [ 5  6]
 [10 11]]


In [45]:
# all element in third column
y = X[:, 2]
print(y)

[ 2  7 12 17]


In [46]:
y = X[:, 2:3]
print(y)

[[ 2]
 [ 7]
 [12]
 [17]]


In [47]:
y = X[2:3, :]
z = X[2, :]
print(y)
print(z)

[[10 11 12 13 14]]
[10 11 12 13 14]


In [48]:
z = X[1:, 2:]
print("X: ")
print(X)
print("z: ")
print(z)


X: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
z: 
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


**Note-** when we perform slices on ndarrays and save them into new variables, as we did above, the data is not copied into the new variable.

In [49]:
z[2, 2] = 333333
print("X: ", X)
print("z: ", z)

X:  [[     0      1      2      3      4]
 [     5      6      7      8      9]
 [    10     11     12     13     14]
 [    15     16     17     18 333333]]
z:  [[     7      8      9]
 [    12     13     14]
 [    17     18 333333]]


In [50]:
# .copy()- It returns a copy of the array

z = X[1:, 2:].copy()
z[2, 2] = 6666
print("X: ", X)
print("z: ", z)

X:  [[     0      1      2      3      4]
 [     5      6      7      8      9]
 [    10     11     12     13     14]
 [    15     16     17     18 333333]]
z:  [[   7    8    9]
 [  12   13   14]
 [  17   18 6666]]


In [51]:
# extract diagonal elements
d = np.diag(X)
print(d)

[ 0  6 12 18]


In [52]:
# extract elements above diagonal
d = np.diag(X, k=1)
print(d)

[     1      7     13 333333]


In [53]:
# extraxt elements below diagonal
d = np.diag(X, k = -1)
print(d)

[ 5 11 17]


In [54]:
# unique elements from array
X = [[1, 2, 3], [2, 3, 3]]
print(np.unique(X))

[1 2 3]


# Boolean Indexing, Set Operations, and Sorting

### Boolean Indexing

slicing array using indices is useful when we are knowing the exact indices of the element wwe want to select
but when we are not knowing the indices of the element we want to select then boolean indexing can be helpful.

In [55]:
X = np.arange(0, 20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [56]:
# select element greater than 10
print(X[X>10])

[11 12 13 14 15 16 17 18 19]


In [57]:
# select element less than 8
print(X[X<=7])

[0 1 2 3 4 5 6 7]


In [58]:
# select all the element with value between 11 & 19
print(X[(X>10)&(X<20)])

[11 12 13 14 15 16 17 18 19]


In [59]:
# replace all the element with value between 11 & 19 with -1
X[(X>10)&(X<20)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


### Set Operation

In [60]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 3, 2, 8, 9])

In [61]:
print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 3]
[1 4 5]
[1 2 3 4 5 6 7 8 9]


### Sorting

**default sort method (X.sort())-**
- The method above sorts an array in-place.that the original array will be changed to the sorted one

**numpy.sort function (np.sort(X))-**
-  it sorts the ndrrays out of place. it doesn't change the original ndarray being sorted.

In [62]:
s = np.random.randint(1, 20, size = (10, ))
print(s)

[18 16 13 17  9 10 15 15 10 16]


In [63]:
print(np.sort(s))
print(s)

[ 9 10 10 13 15 15 16 16 17 18]
[18 16 13 17  9 10 15 15 10 16]


In [64]:
s = np.random.randint(1, 20, size = (10, ))
print(s)
s.sort()
print(s)

[13 13  5 11  9  7  8 17  8 16]
[ 5  7  8  8  9 11 13 13 16 17]


In [65]:
s = np.random.randint(1, 20, size = (5, 5))
print(s)

[[17 10  9 12  6]
 [11 18 10  2  5]
 [ 9 12 16 18 17]
 [ 6 14 17 15  6]
 [ 3 18  3 12  3]]


In [66]:
# sort column wise
print(np.sort(s, axis = 0))

[[ 3 10  3  2  3]
 [ 6 12  9 12  5]
 [ 9 14 10 12  6]
 [11 18 16 15  6]
 [17 18 17 18 17]]


In [67]:
# sort row wise
print(np.sort(s, axis = 1))

[[ 6  9 10 12 17]
 [ 2  5 10 11 18]
 [ 9 12 16 17 18]
 [ 6  6 14 15 17]
 [ 3  3  3 12 18]]


# Arithmetic operations and Broadcasting

NumPy allows element-wise operations on ndarrays as well as matrix operations. In order to do element-wise operations, NumPy sometimes uses something called Broadcasting. Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.

In [68]:
# Element-wise arithmetic operations on 1-D arrays

x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

print("x: ", x, "\ny: ", y)
print("\n")

# addition
print("add: ", x+y)
print("add: ", np.add(x, y))
print("\n")

# subtraction
print("subtract: ", x-y)
print("subtract: ", np.subtract(x, y))
print("\n")

# multiplication
print("multiply: ", x*y)
print("multiply: ", np.multiply(x, y))
print("\n")

# division
print("divide: ", x/y)
print("divide: ", np.divide(x, y))
print("\n")

x:  [1 2 3 4 5 6] 
y:  [4.5 5.5 6.5 7.5 8.5 9.5]


add:  [ 5.5  7.5  9.5 11.5 13.5 15.5]
add:  [ 5.5  7.5  9.5 11.5 13.5 15.5]


subtract:  [-3.5 -3.5 -3.5 -3.5 -3.5 -3.5]
subtract:  [-3.5 -3.5 -3.5 -3.5 -3.5 -3.5]


multiply:  [ 4.5 11.  19.5 30.  42.5 57. ]
multiply:  [ 4.5 11.  19.5 30.  42.5 57. ]


divide:  [0.22222222 0.36363636 0.46153846 0.53333333 0.58823529 0.63157895]
divide:  [0.22222222 0.36363636 0.46153846 0.53333333 0.58823529 0.63157895]




In [69]:
# Element-wise arithmetic operations on a 2-D array (Same shape)

x = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
y = np.array([4.5, 5.5, 6.5, 7.5, 8.5, 9.5]).reshape(2, 3)

print("x: \n", x, "\ny: \n", y)
print("\n")

# addition
print("add: \n", x+y)
print("add: \n", np.add(x, y))
print("\n")

# subtraction
print("subtract: \n", x-y)
print("subtract: \n", np.subtract(x, y))
print("\n")

# multiplication\n
print("multiply: \n", x*y)
print("multiply: \n", np.multiply(x, y))
print("\n")

# division
print("divide: \n", x/y)
print("divide: \n", np.divide(x, y))
print("\n")

x: 
 [[1 2 3]
 [4 5 6]] 
y: 
 [[4.5 5.5 6.5]
 [7.5 8.5 9.5]]


add: 
 [[ 5.5  7.5  9.5]
 [11.5 13.5 15.5]]
add: 
 [[ 5.5  7.5  9.5]
 [11.5 13.5 15.5]]


subtract: 
 [[-3.5 -3.5 -3.5]
 [-3.5 -3.5 -3.5]]
subtract: 
 [[-3.5 -3.5 -3.5]
 [-3.5 -3.5 -3.5]]


multiply: 
 [[ 4.5 11.  19.5]
 [30.  42.5 57. ]]
multiply: 
 [[ 4.5 11.  19.5]
 [30.  42.5 57. ]]


divide: 
 [[0.22222222 0.36363636 0.46153846]
 [0.53333333 0.58823529 0.63157895]]
divide: 
 [[0.22222222 0.36363636 0.46153846]
 [0.53333333 0.58823529 0.63157895]]




In [70]:
# Additional mathematical functions

x = np.array([1, 3, 5, 7, 9])

print("exponent: \n", np.exp(x))
print("square root: \n", np.sqrt(x))
print("power: \n", np.power(x, 3))

exponent: 
 [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 8.10308393e+03]
square root: 
 [1.         1.73205081 2.23606798 2.64575131 3.        ]
power: 
 [  1  27 125 343 729]


In [71]:
# Statistical functions

x = np.arange(1, 5).reshape(2, 2)
print("x: \n", x)


print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()

print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()

print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()

print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()

print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()

print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

x: 
 [[1 2]
 [3 4]]
Average of all elements in X: 2.3
Average of all elements in the columns of X: [3.5  1.25 1.75 2.25 2.75]
Average of all elements in the rows of X: [ 2.   7.   1.2 -1. ]

Sum of all elements in X: 46
Sum of all elements in the columns of X: [14  5  7  9 11]
Sum of all elements in the rows of X: [10 35  6 -5]

Standard Deviation of all elements in X: 3.7960505792204615
Standard Deviation of all elements in the columns of X: [4.38748219 2.86138079 3.26917421 3.69966215 4.14578099]
Standard Deviation of all elements in the rows of X: [1.41421356 1.41421356 4.4        0.        ]

Median of all elements in X: 0.5
Median of all elements in the columns of X: [2.5 0.  0.5 1.  1.5]
Median of all elements in the rows of X: [ 2.  7. -1. -1.]

Maximum value of all elements in X: 10
Maximum value of all elements in the columns of X: [10  6  7  8  9]
Maximum value of all elements in the rows of X: [ 4  9 10 -1]

Minimum value of all elements in X: -1
Minimum value of all element

In [72]:
# Change value of all elements of an array

print(x)
print()

print('3 * X = \n', 3 * X)
print('3 + X = \n', 3 + X)
print('X - 3 = \n', X - 3)
print('X / 3 = \n', X / 3)

[[1 2]
 [3 4]]

3 * X = 
 [[ 0  3  6  9 12]
 [15 18 21 24 27]
 [30 -3 -3 -3 -3]
 [-3 -3 -3 -3 -3]]
3 + X = 
 [[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13  2  2  2  2]
 [ 2  2  2  2  2]]
X - 3 = 
 [[-3 -2 -1  0  1]
 [ 2  3  4  5  6]
 [ 7 -4 -4 -4 -4]
 [-4 -4 -4 -4 -4]]
X / 3 = 
 [[ 0.          0.33333333  0.66666667  1.          1.33333333]
 [ 1.66666667  2.          2.33333333  2.66666667  3.        ]
 [ 3.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]]


In [73]:
# Use Broadcasting to create a 4 x 4 ndarray that has its first column full of 1s, its second column full of 2s, its third column full of 3s, etc.. 

In [74]:
X = np.ones((4, 4))*np.arange(1, 5)
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


# **Summary**

- General Purpose

| Function/Method | Description | 
| --- | --- | 
| numpy.ndarray.dtype | data-type of the elements of the array | 
| numpy.ndarray.ndim | number of array-dimensions (rank) |
| numpy.ndarray.shape | tuple representing the array dimensions |
| numpy.ndarray.size | number of elements present in the array |
| numpy.save | Save an array to .npy (numpy) format |
| numpy.load | Load array from the .npy files |
| numpy.random.random | Return random floats values from the interval [0.0, 1.0), in a specified shape |
| numpy.random.randint | random integers from the half-open interval [a, b), in a specified shape |
| numpy.random.normal | random samples from a Gaussian (normal) distribution |
| numpy.random.permutation | randomly permuted sequence from the given list |
| numpy.ndarray.reshape | array containing the same elements with a new shape |

- Array Creation

| Function/Method | Description | 
| --- | --- | 
| numpy.ones | array of given shape and type, filled with 1s. |
| numpy.zeros | array of given shape and type, filled with 0s. |
| numpy.full | array of given shape and type, filled with a specific value. |
| numpy.eye | 2-D identity matrix |
| numpy.diag | Extract the diagonal elements |
| numpy.unique | sorted unique elements of an array |
| numpy.array | Create an n-dimensional array |
| numpy.arange | evenly spaced values within a given half-open interval [a, b) |
| numpy.linspace |  evenly spaced numbers over a specified interval [a,b] |
| numpy.ndarray.copy |  copy of the array |


- Operating with Elements and Indices

| Function/Method | Description | 
| --- | --- |
| numpy.insert | Insert values along the given axis before the specified indices |
| numpy.delete | Return a new array, after deleting sub-arrays along a specified axis |
| numpy.append | Append values at the end of the specified array |
| numpy.hstack | Return a stacked array formed by stacking the given arrays in sequence horizontally (column-wise) |
| numpy.vstack | Return a stacked array formed by stacking the given arrays, will be at least 2-D, in sequence vertically (row-wise) |
| numpy.sort | Return a sorted copy of an array |
| numpy.ndarray.sort | Sort an array in-place |

- Set Operations

| Function/Method | Description | 
| --- | --- |
| numpy.intersect1d | intersection of two arrays |
| numpy.setdiff1d | set difference of two arrays |
| numpy.union1d | unique, sorted array of values that are in either of the two input arrays |

- Arithmetic and Statistical Operations

| Function/Method | Description | 
| --- | --- |
| numpy.add | Element-wise addition |
| numpy.subtract | 	Subtract arguments of given arrays, element-wise |
| numpy.multiply | Multiply arguments of given arrays, element-wise |
| numpy.divide | true division of the inputs, element-wise |
| numpy.exp |  exponential of all elements in the input array |
| numpy.power | First array elements raised to powers from second array, element-wise |
| numpy.sqrt | non-negative square-root of an array, element-wise |
| numpy.ndarray.min | minimum along the specified axis |
| numpy.ndarray.max | maximum along a given axis |
| numpy.mean / numpy.ndarray.mean | arithmetic mean along the specified axis |
| numpy.median | median along the specified axis |