<a href="https://www.kaggle.com/code/himanshunakrani/numpy?scriptVersionId=106292748" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# What is NumPy?

- NumPy is the fundamental package for scientific computing in Python. it is used for working with arrays. 
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy stands for Numerical Python.

# install NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Why Use NumPy?

Even though Python lists are great on their own, NumPy has a number of key features that give it great advantages over Python lists.

### Benefits of using NumPy

**1) Speed** -  When performing operations on large arrays NumPy can often perform several orders of magnitude faster than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.<br> 
**2) multidimensional array data structures** -  NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently, making it very suitable for solving machine learning problems.<br>
**3) optimized built-in mathematical functions** - Another great advantage of NumPy over Python lists is that NumPy has a large number of optimized built-in mathematical functions. These functions allow you to do a variety of complex mathematical computations very fast and with very little code making your programs more readable and easier to understand.

## 1. Speed

In [2]:
# Why use NumPy?
import time
import numpy as np
x = np.random.random(100000000)

# Case 1
start = time.time()
sum(x) / len(x)
print("using built-in python function: ", time.time() - start)

# Case 2
start = time.time()
np.mean(x)
print("using NumPy: ", time.time() - start)

using built-in python function:  8.623758316040039
using NumPy:  0.06952428817749023


# Creating NumPy array

### 1. Using regular Python lists

In [3]:
import numpy as np

In [4]:
#  a 1-D Array of Integers (Rank #1 Array)

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print("rank: ", a.ndim)

rank:  1


In [6]:
print(a.shape)

(5,)


In [7]:
print(a.dtype)

int64


In [8]:
# 2-D Array (Rank #2 Array)

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
print(b.shape)

(3, 4)


In [10]:
print("rank: ", b.ndim)

rank:  2


In [11]:
# 1-D Array of Strings (Rank #1 Array)

c = np.array(["Hello", "World"])
print(c.dtype)

<U5


In [12]:
# 1-D Array of Int and String (Rank #1 Array)

d = np.array([1, 2, 3, "Hello"])
print(d.dtype)

<U21


In [13]:
# 1-D Array of Int and Float

e = np.array([1, 2.3, 5])
print(e.dtype)

float64


In [14]:
# 1-D Array of Float, and specifying the datatype of each element as int64

f = np.array([1, 2.3, 4], dtype = np.int64)
print(f.dtype)

int64


In [15]:
#  Save the NumPy array to a File
x = np.array([1, 2, 3, 4, 5])

# save x into the current directory as 'my_array'
np.save('my_array', x)

In [16]:
# load the saved array from current directory into variable y
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


### 2. Using built-in NumPy functions

In [17]:
# 3X4 ndarray full of zeros

X = np.zeros((3, 4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# 3X4 ndarray full of ones

Y = np.ones((3, 4))
print(Y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# 3X4 ndarray full of sevens

Z = np.full((3, 4), 7)
print(Z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [20]:
# 5X5 identity matrix

I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
# 4X4 diagonal matrix having diagonal values 1, 2, 3 and 4

D = np.diag([1, 2, 3, 4])
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [22]:
# rank 1 ndarray that has sequential integers from 0 to 9
N = np.arange(10)

# rank 1 ndarray that has sequential integers from 10 to 29
M = np.arange(10, 30)

# rank 1 ndarray that has evenly spaced integers from 10 to 30 in steps of 3
O = np.arange(10, 30, 3)
print(N)
print(M)
print(O)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[10 13 16 19 22 25 28]


In [23]:
# rank 1 ndarray that has 50 intgers evenly spaced between 10and 30
Q = np.linspace(10, 30, 50)
print(Q)

[10.         10.40816327 10.81632653 11.2244898  11.63265306 12.04081633
 12.44897959 12.85714286 13.26530612 13.67346939 14.08163265 14.48979592
 14.89795918 15.30612245 15.71428571 16.12244898 16.53061224 16.93877551
 17.34693878 17.75510204 18.16326531 18.57142857 18.97959184 19.3877551
 19.79591837 20.20408163 20.6122449  21.02040816 21.42857143 21.83673469
 22.24489796 22.65306122 23.06122449 23.46938776 23.87755102 24.28571429
 24.69387755 25.10204082 25.51020408 25.91836735 26.32653061 26.73469388
 27.14285714 27.55102041 27.95918367 28.36734694 28.7755102  29.18367347
 29.59183673 30.        ]


In [24]:
#  reshape M into a 5X4 ndarray
m = M.reshape(5, 4)
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]


In [25]:
n = np.arange(0, 100).reshape(10, 10)
print(n)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [26]:
# 3X3 ndarray with random floats in the half-open interval [0.0, 1.0)
r = np.random.random((5, 5))
print(r)

[[0.79448468 0.68516896 0.65936191 0.22974885 0.30228335]
 [0.37390105 0.14267262 0.85782313 0.20559689 0.30969167]
 [0.04708095 0.17957463 0.73404135 0.2280103  0.18525412]
 [0.23329633 0.99442586 0.16175465 0.48014693 0.91886312]
 [0.05439005 0.33284413 0.99947315 0.02081679 0.44244488]]


In [27]:
#  5X4 ndarray with random integers in the half-open interval [4, 20)
r = np.random.randint(4, 20, (5, 4))
print(r)

[[ 5 13  7  8]
 [13 16 10  4]
 [ 5  9  6 10]
 [14 18  8  5]
 [13 10 18 19]]


In [28]:
# normal(Gaussian) distribution, mean = 0, standard deviation = 0.1

r = np.random.normal(0, 0.1, size = (100, 100))

print("mean: ", r.mean())
print("std: ", r.std())
print("max: ", r.max())
print("min: ", r.min())
print("Positive: ", (r>0).sum())
print("Negative: ", (r<0).sum())

mean:  0.00011752439263908431
std:  0.09865194327921083
max:  0.41003517103173337
min:  -0.3607279872768128
Positive:  4996
Negative:  5004


# Accessing, Deleting, and Inserting Elements Into ndarrays

In [29]:
# indexing

x = np.array([1, 2, 3, 4, 5])

In [30]:
print("1st element: ", x[0])
print("2nd element: ", x[1])
print("3rd element: ", x[2])
print("5th element: ", x[4])

1st element:  1
2nd element:  2
3rd element:  3
5th element:  5


In [31]:
# negative indexing
print("1st element: ", x[-5])
print("2nd element: ", x[-4])
print("3rd element: ", x[-3])
print("5th element: ", x[-1])


1st element:  1
2nd element:  2
3rd element:  3
5th element:  5


In [32]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print("element at (0, 0): ", y[0, 0])
print("element at (1, 2): ", y[1, 2])
print("element at (2, 1): ", y[2, 1])

element at (0, 0):  1
element at (1, 2):  6
element at (2, 1):  8


In [34]:
# modifying element

y[0, 0] = 100
print(y)


[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [35]:
# deleting element

X = np.delete(x, [0, 4])
print(X)

[2 3 4]


In [36]:
Y = np.delete(y, [0, 0])
print(Y)

[2 3 4 5 6 7 8 9]


In [37]:
# appending an element

W = np.append(y, [[10, 20, 30]], axis = 0)
print(W)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  20  30]]


In [38]:
V = np.append(y, [[10], [20], [30]], axis = 1)
print(V)

[[100   2   3  10]
 [  4   5   6  20]
 [  7   8   9  30]]


In [39]:
# inserting an element at a position

Z = np.insert(W, 2, [9, 8, 7], axis = 0)
print(Z)

[[100   2   3]
 [  4   5   6]
 [  9   8   7]
 [  7   8   9]
 [ 10  20  30]]


In [40]:
x = np.array([1,2])
y = np.array([[3,4],[5,6]])


# stack x on top of Y
K = np.vstack((x, y))
print("K:\n", K)

# x on the right of Y
M = np.hstack((y,x.reshape(2,1)))
print("M:\n", M)

K:
 [[1 2]
 [3 4]
 [5 6]]
M:
 [[3 4 1]
 [5 6 2]]


# Slicing ndarrays

In [41]:
X = np.arange(0, 20).reshape(4, 5)